export type AddressDetailedInfo = {
  street: string
  postalCode: string
  city: string
  jurisdiction: string
}

export type AlphabetStringResult = {
  value: string
  location?: Rectangle
  side?: ScanningSide
}

export type AlphabetType = "latin" | "arabic" | "cyrillic" | "greek"

export type BarcodeData = {
  barcodeType: BarcodeType
  uncertain: boolean
  stringData: string
  rawData: Uint8Array
}

export type BarcodeElement = {
  key: BarcodeElementKey
  value: string
}

export type BarcodeElementKey =
  | "document-type"
  | "standard-version-number"
  | "customer-family-name"
  | "customer-first-name"
  | "customer-full-name"
  | "date-of-birth"
  | "sex"
  | "eye-color"
  | "address-street"
  | "address-city"
  | "address-jurisdiction-code"
  | "address-postal-code"
  | "full-address"
  | "height"
  | "height-in"
  | "height-cm"
  | "customer-middle-name"
  | "hair-color"
  | "name-suffix"
  | "aka-full-name"
  | "aka-family-name"
  | "aka-given-name"
  | "aka-suffix-name"
  | "weight-range"
  | "weight-pounds"
  | "weight-kilograms"
  | "customer-id-number"
  | "family-name-truncation"
  | "first-name-truncation"
  | "middle-name-truncation"
  | "place-of-birth"
  | "address-street-2"
  | "race-ethnicity"
  | "name-prefix"
  | "country-identification"
  | "residence-street-address"
  | "residence-street-address-2"
  | "residence-city"
  | "residence-jurisdiction-code"
  | "residence-postal-code"
  | "residence-full-address"
  | "under-18"
  | "under-19"
  | "under-21"
  | "social-security-number"
  | "aka-social-security-number"
  | "aka-middle-name"
  | "aka-prefix-name"
  | "organ-donor"
  | "veteran"
  | "aka-date-of-birth"
  | "issuer-identification-number"
  | "document-expiration-date"
  | "jurisdiction-version-number"
  | "jurisdiction-vehicle-class"
  | "jurisdiction-restriction-codes"
  | "jurisdiction-endorsement-codes"
  | "document-issue-date"
  | "federal-commercial-vehicle-codes"
  | "issuing-jurisdiction"
  | "standard-vehicle-classification"
  | "issuing-jurisdiction-name"
  | "standard-endorsement-code"
  | "standard-restriction-code"
  | "jurisdiction-vehicle-classification-description"
  | "jurisdiction-endorsement-code-description"
  | "jurisdiction-restriction-code-description"
  | "inventory-control-number"
  | "card-revision-date"
  | "document-discriminator"
  | "limited-duration-document"
  | "audit-information"
  | "compliance-type"
  | "issue-timestamp"
  | "permit-expiration-date"
  | "permit-identifier"
  | "permit-issue-date"
  | "number-of-duplicates"
  | "hazmat-expiration-date"
  | "medical-indicator"
  | "non-resident"
  | "unique-customer-id"
  | "data-discriminator"
  | "document-expiration-month"
  | "document-nonexpiring"
  | "security-version"

export type BarcodeResult = {
  barcodeData: BarcodeData
  firstName: string
  middleName: string
  lastName: string
  fullName: string
  additionalNameInformation: string
  address: string
  placeOfBirth: string
  nationality: string
  race: string
  religion: string
  profession: string
  maritalStatus: string
  residentialStatus: string
  employer: string
  sex: string
  dateOfBirth: DateResult<string>
  dateOfIssue: DateResult<string>
  dateOfExpiry: DateResult<string>
  documentNumber: string
  personalIdNumber: string
  documentAdditionalNumber: string
  issuingAuthority: string
  addressDetailedInfo: AddressDetailedInfo
  driverLicenseDetailedInfo: DriverLicenceDetailedInfo<string>
  extendedElements: Array<BarcodeElement>
}

export type BarcodeType =
  | "qr-code"
  | "data-matrix"
  | "upc-e"
  | "upc-a"
  | "ean-8"
  | "ean-13"
  | "code-128"
  | "code-39"
  | "itf"
  | "aztec-barcode"
  | "pdf417-barcode"

export type DocumentScanReport = {
  mode?: RecognitionMode
  documentClassInfo: DocumentClassInfo
  dataMatchResult?: DataMatchResult
  firstName?: StringResult
  lastName?: StringResult
  fullName?: StringResult
  additionalNameInformation?: StringResult
  localizedName?: StringResult
  fathersName?: StringResult
  mothersName?: StringResult
  address?: StringResult
  additionalAddressInformation?: StringResult
  additionalOptionalAddressInformation?: StringResult
  placeOfBirth?: StringResult
  nationality?: StringResult
  race?: StringResult
  religion?: StringResult
  profession?: StringResult
  maritalStatus?: StringResult
  residentialStatus?: StringResult
  employer?: StringResult
  sex?: StringResult
  sponsor?: StringResult
  bloodType?: StringResult
  documentNumber?: StringResult
  personalIdNumber?: StringResult
  documentAdditionalNumber?: StringResult
  documentOptionalAdditionalNumber?: StringResult
  additionalPersonalIdNumber?: StringResult
  issuingAuthority?: StringResult
  documentSubtype?: StringResult
  remarks?: StringResult
  residencePermitType?: StringResult
  manufacturingYear?: StringResult
  vehicleType?: StringResult
  eligibilityCategory?: StringResult
  specificDocumentValidity?: StringResult
  visaType?: StringResult
  vehicleOwner?: StringResult
  certificateNumber?: StringResult
  countryCode?: StringResult
  nationalInsuranceNumber?: StringResult
  dateOfBirth?: DateResult<StringResult>
  dateOfIssue?: DateResult<StringResult>
  dateOfExpiry?: DateResult<StringResult>
  dateOfExpiryPermanent?: boolean
  driverLicenseDetailedInfo?: DriverLicenceDetailedInfo<StringResult>
  dependentsInfo?: DependentInfo[]
  inputImagesScanningSide?: ScanningSide[]
  barcodeInputImageScanningSide?: ScanningSide
  documentImagesScanningSide?: ScanningSide[]
  faceImageScanningSide?: ScanningSide
  signatureImageScanningSide?: ScanningSide
  subResults: SingleSideScanningResult[]
}

export type Country =
  | "albania"
  | "algeria"
  | "argentina"
  | "australia"
  | "austria"
  | "azerbaijan"
  | "bahrain"
  | "bangladesh"
  | "belgium"
  | "bosnia-and-herzegovina"
  | "brunei"
  | "bulgaria"
  | "cambodia"
  | "canada"
  | "chile"
  | "colombia"
  | "costa-rica"
  | "croatia"
  | "cyprus"
  | "czechia"
  | "denmark"
  | "dominican-republic"
  | "egypt"
  | "estonia"
  | "finland"
  | "france"
  | "georgia"
  | "germany"
  | "ghana"
  | "greece"
  | "guatemala"
  | "hong-kong"
  | "hungary"
  | "india"
  | "indonesia"
  | "ireland"
  | "israel"
  | "italy"
  | "jordan"
  | "kazakhstan"
  | "kenya"
  | "kosovo"
  | "kuwait"
  | "latvia"
  | "lithuania"
  | "malaysia"
  | "maldives"
  | "malta"
  | "mauritius"
  | "mexico"
  | "morocco"
  | "netherlands"
  | "new-zealand"
  | "nigeria"
  | "pakistan"
  | "panama"
  | "paraguay"
  | "philippines"
  | "poland"
  | "portugal"
  | "puerto-rico"
  | "qatar"
  | "romania"
  | "russia"
  | "saudi-arabia"
  | "serbia"
  | "singapore"
  | "slovakia"
  | "slovenia"
  | "south-africa"
  | "spain"
  | "sweden"
  | "switzerland"
  | "taiwan"
  | "thailand"
  | "tunisia"
  | "turkey"
  | "uae"
  | "uganda"
  | "uk"
  | "ukraine"
  | "usa"
  | "vietnam"
  | "brazil"
  | "norway"
  | "oman"
  | "ecuador"
  | "el-salvador"
  | "sri-lanka"
  | "peru"
  | "uruguay"
  | "bahamas"
  | "bermuda"
  | "bolivia"
  | "china"
  | "european-union"
  | "haiti"
  | "honduras"
  | "iceland"
  | "japan"
  | "luxembourg"
  | "montenegro"
  | "nicaragua"
  | "south-korea"
  | "venezuela"
  | "afghanistan"
  | "aland-islands"
  | "american-samoa"
  | "andorra"
  | "angola"
  | "anguilla"
  | "antarctica"
  | "antigua-and-barbuda"
  | "armenia"
  | "aruba"
  | "bailiwick-of-guernsey"
  | "bailiwick-of-jersey"
  | "barbados"
  | "belarus"
  | "belize"
  | "benin"
  | "bhutan"
  | "bonaire-saint-eustatius-and-saba"
  | "botswana"
  | "bouvet-island"
  | "british-indian-ocean-territory"
  | "burkina-faso"
  | "burundi"
  | "cameroon"
  | "cape-verde"
  | "caribbean-netherlands"
  | "cayman-islands"
  | "central-african-republic"
  | "chad"
  | "christmas-island"
  | "cocos-islands"
  | "comoros"
  | "congo"
  | "cook-islands"
  | "cuba"
  | "curacao"
  | "democratic-republic-of-the-congo"
  | "djibouti"
  | "dominica"
  | "east-timor"
  | "equatorial-guinea"
  | "eritrea"
  | "ethiopia"
  | "falkland-islands"
  | "faroe-islands"
  | "federated-states-of-micronesia"
  | "fiji"
  | "french-guiana"
  | "french-polynesia"
  | "french-southern-territories"
  | "gabon"
  | "gambia"
  | "gibraltar"
  | "greenland"
  | "grenada"
  | "guadeloupe"
  | "guam"
  | "guinea"
  | "guinea-bissau"
  | "guyana"
  | "heard-island-and-mcdonald-islands"
  | "iran"
  | "iraq"
  | "isle-of-man"
  | "ivory-coast"
  | "jamaica"
  | "kiribati"
  | "kyrgyzstan"
  | "laos"
  | "lebanon"
  | "lesotho"
  | "liberia"
  | "libya"
  | "liechtenstein"
  | "macau"
  | "madagascar"
  | "malawi"
  | "mali"
  | "marshall-islands"
  | "martinique"
  | "mauritania"
  | "mayotte"
  | "moldova"
  | "monaco"
  | "mongolia"
  | "montserrat"
  | "mozambique"
  | "myanmar"
  | "namibia"
  | "nauru"
  | "nepal"
  | "new-caledonia"
  | "niger"
  | "niue"
  | "norfolk-island"
  | "northern-cyprus"
  | "northern-mariana-islands"
  | "north-korea"
  | "north-macedonia"
  | "palau"
  | "palestine"
  | "papua-new-guinea"
  | "pitcairn"
  | "reunion"
  | "rwanda"
  | "saint-barthelemy"
  | "saint-helena-ascension-and-tristian-da-cunha"
  | "saint-kitts-and-nevis"
  | "saint-lucia"
  | "saint-martin"
  | "saint-pierre-and-miquelon"
  | "saint-vincent-and-the-grenadines"
  | "samoa"
  | "san-marino"
  | "sao-tome-and-principe"
  | "senegal"
  | "seychelles"
  | "sierra-leone"
  | "sint-maarten"
  | "solomon-islands"
  | "somalia"
  | "south-georgia-and-the-south-sandwich-islands"
  | "south-sudan"
  | "sudan"
  | "suriname"
  | "svalbard-and-jan-mayen"
  | "eswatini"
  | "syria"
  | "tajikistan"
  | "tanzania"
  | "togo"
  | "tokelau"
  | "tonga"
  | "trinidad-and-tobago"
  | "turkmenistan"
  | "turks-and-caicos-islands"
  | "tuvalu"
  | "united-states-minor-outlying-islands"
  | "uzbekistan"
  | "vanuatu"
  | "vatican-city"
  | "virgin-islands-british"
  | "virgin-islands-us"
  | "wallis-and-futuna"
  | "western-sahara"
  | "yemen"
  | "yugoslavia"
  | "zambia"
  | "zimbabwe"
  | "schengen-area"

export type DataMatchFieldState = {
  fieldType: DataMatchFieldType
  state: DataMatchState
}

export type DataMatchFieldType =
  | "date-of-birth"
  | "date-of-expiry"
  | "document-number"
  | "document-additional-number"
  | "document-optional-additional-number"
  | "personal-id-number"

export type DataMatchResult = {
  statePerField?: DataMatchFieldState[]
  overallState: DataMatchState
}

export type DataMatchState = "not-performed" | "failed" | "success"

export type DateResult<S extends string | StringResult> = {
  day?: number
  month?: number
  year?: number
  originalString?: S
  filledByDomainKnowledge: boolean
  successfullyParsed?: boolean
}

export type DependentInfo = {
  dateOfBirth?: DateResult<StringResult>
  sex?: StringResult
  documentNumber?: StringResult
  fullName?: StringResult
}

export type DetailedCroppedImageResult = {
  image: ImageData
  location?: Rectangle
  side?: ScanningSide
}

export type DocumentClassInfo = {
  country?: Country
  region?: Region
  type?: DocumentType
  countryName?: string
  isoNumericCountryCode?: string
  isoAlpha2CountryCode?: string
  isoAlpha3CountryCode?: string
}

export type DocumentType =
  | "consular-id"
  | "dl"
  | "dl-public-services-card"
  | "employment-pass"
  | "fin-card"
  | "id"
  | "multipurpose-id"
  | "mykad"
  | "mykid"
  | "mypr"
  | "mytentera"
  | "pan-card"
  | "professional-id"
  | "public-services-card"
  | "residence-permit"
  | "resident-id"
  | "temporary-residence-permit"
  | "voter-id"
  | "work-permit"
  | "ikad"
  | "military-id"
  | "mykas"
  | "social-security-card"
  | "health-insurance-card"
  | "passport"
  | "s-pass"
  | "address-card"
  | "alien-id"
  | "alien-passport"
  | "green-card"
  | "minors-id"
  | "postal-id"
  | "professional-dl"
  | "tax-id"
  | "weapon-permit"
  | "visa"
  | "border-crossing-card"
  | "driver-card"
  | "global-entry-card"
  | "mypolis"
  | "nexus-card"
  | "passport-card"
  | "proof-of-age-card"
  | "refugee-id"
  | "tribal-id"
  | "veteran-id"
  | "citizenship-certificate"
  | "my-number-card"
  | "consular-passport"
  | "minors-passport"
  | "minors-public-services-card"
  | "driving-privilege-card"
  | "asylum-request"
  | "driver-qualification-card"
  | "provisional-dl"
  | "refugee-passport"
  | "special-id"
  | "uniformed-services-id"
  | "immigrant-visa"
  | "consular-voter-id"
  | "twic-card"
  | "exit-entry-permit"
  | "mainland-travel-permit-taiwan"
  | "nbi-clearance"
  | "proof-of-registration"
  | "temporary-protection-permit"
  | "afghan-citizen-card"
  | "eid"
  | "pass"
  | "sis-id"
  | "asic-card"
  | "bidoon-card"
  | "interim-health-insurance-card"
  | "non-voter-id"
  | "reciprocal-health-insurance-card"
  | "vehicle-registration"
  | "esaad-card"
  | "registration-certificate"
  | "medical-marijuana-id"
  | "non-card-tribal-id"
  | "diplomatic-id"

export type DriverLicenceDetailedInfo<S extends string | StringResult> = {
  restrictions?: S
  endorsements?: S
  vehicleClass?: S
  conditions?: S
  vehicleClassesInfo?: VehicleClassInfo<S>[]
}

export type MrzDocumentType =
  | "unknown"
  | "identity-card"
  | "passport"
  | "visa"
  | "green-card"
  | "mys-pass-imm13p"
  | "driver-license"
  | "internal-travel-document"
  | "border-crossing-card"

export type MrzResult = {
  rawMrzString: string
  documentCode: string
  issuer: string
  documentNumber: string
  opt1: string
  opt2: string
  gender: string
  nationality: string
  primaryId: string
  secondaryId: string
  issuerName: string
  nationalityName: string
  verified: boolean
  dateOfBirth: Date
  dateOfExpiry: Date
  documentType: MrzDocumentType
  sanitizedOpt1: string
  sanitizedOpt2: string
  sanitizedNationality: string
  sanitizedIssuer: string
  sanitizedDocumentCode: string
  sanitizedDocumentNumber: string
}

export type RecognitionMode =
  | "mrz-id"
  | "mrz-visa"
  | "mrz-passport"
  | "photo-id"
  | "full-recognition"
  | "barcode-id"

export type RecognitionModeFilter = {
  enableMrzId: boolean
  enableMrzVisa: boolean
  enableMrzPassport: boolean
  enablePhotoId: boolean
  enableBarcodeId: boolean
  enableFullDocumentRecognition: boolean
}

export type Rectangle = {
  x: number
  y: number
  width: number
  height: number
}

export type Region =
  | "alabama"
  | "alaska"
  | "alberta"
  | "arizona"
  | "arkansas"
  | "australian-capital-territory"
  | "british-columbia"
  | "california"
  | "colorado"
  | "connecticut"
  | "delaware"
  | "district-of-columbia"
  | "florida"
  | "georgia"
  | "hawaii"
  | "idaho"
  | "illinois"
  | "indiana"
  | "iowa"
  | "kansas"
  | "kentucky"
  | "louisiana"
  | "maine"
  | "manitoba"
  | "maryland"
  | "massachusetts"
  | "michigan"
  | "minnesota"
  | "mississippi"
  | "missouri"
  | "montana"
  | "nebraska"
  | "nevada"
  | "new-brunswick"
  | "new-hampshire"
  | "new-jersey"
  | "new-mexico"
  | "new-south-wales"
  | "new-york"
  | "northern-territory"
  | "north-carolina"
  | "north-dakota"
  | "nova-scotia"
  | "ohio"
  | "oklahoma"
  | "ontario"
  | "oregon"
  | "pennsylvania"
  | "quebec"
  | "queensland"
  | "rhode-island"
  | "saskatchewan"
  | "south-australia"
  | "south-carolina"
  | "south-dakota"
  | "tasmania"
  | "tennessee"
  | "texas"
  | "utah"
  | "vermont"
  | "victoria"
  | "virginia"
  | "washington"
  | "western-australia"
  | "west-virginia"
  | "wisconsin"
  | "wyoming"
  | "yukon"
  | "ciudad-de-mexico"
  | "jalisco"
  | "newfoundland-and-labrador"
  | "nuevo-leon"
  | "baja-california"
  | "chihuahua"
  | "guanajuato"
  | "guerrero"
  | "mexico"
  | "michoacan"
  | "new-york-city"
  | "tamaulipas"
  | "veracruz"
  | "chiapas"
  | "coahuila"
  | "durango"
  | "guerrero-cocula"
  | "guerrero-juchitan"
  | "guerrero-tepecoacuilco"
  | "guerrero-tlacoapa"
  | "gujarat"
  | "hidalgo"
  | "karnataka"
  | "kerala"
  | "khyber-pakhtunkhwa"
  | "madhya-pradesh"
  | "maharashtra"
  | "morelos"
  | "nayarit"
  | "oaxaca"
  | "puebla"
  | "punjab"
  | "queretaro"
  | "san-luis-potosi"
  | "sinaloa"
  | "sonora"
  | "tabasco"
  | "tamil-nadu"
  | "yucatan"
  | "zacatecas"
  | "aguascalientes"
  | "baja-california-sur"
  | "campeche"
  | "colima"
  | "quintana-roo-benito-juarez"
  | "quintana-roo"
  | "quintana-roo-solidaridad"
  | "tlaxcala"
  | "quintana-roo-cozumel"
  | "sao-paolo"
  | "rio-de-janeiro"
  | "rio-grande-do-sul"
  | "northwest-territories"
  | "nunavut"
  | "prince-edward-island"
  | "distrito-federal"
  | "maranhao"
  | "mato-grosso"
  | "minas-gerais"
  | "para"
  | "parana"
  | "pernambuco"
  | "santa-catarina"
  | "andhra-pradesh"
  | "ceara"
  | "goias"
  | "guerrero-acapulco-de-juarez"
  | "haryana"
  | "sergipe"
  | "alagoas"
  | "bangsamoro"

export type ScanningSide = "first" | "second"

export type SingleSideScanningResult = {
  viz?: VizResult
  mrz?: MrzResult
  barcode?: BarcodeResult
  inputImage?: ImageData
  barcodeInputImage?: ImageData
  documentImage?: ImageData
  faceImage?: DetailedCroppedImageResult
  signatureImage?: DetailedCroppedImageResult
}

export type StringResult = {
  [key in AlphabetType]: AlphabetStringResult
}

export type VehicleClassInfo<S extends string | StringResult> = {
  vehicleClass?: S
  licenceType?: S
  effectiveDate?: DateResult<S>
  expiryDate?: DateResult<S>
}

export type VizResult = {
  firstName?: StringResult
  lastName?: StringResult
  fullName?: StringResult
  additionalNameInformation?: StringResult
  localizedName?: StringResult
  fathersName?: StringResult
  mothersName?: StringResult
  address?: StringResult
  additionalAddressInformation?: StringResult
  additionalOptionalAddressInformation?: StringResult
  placeOfBirth?: StringResult
  nationality?: StringResult
  race?: StringResult
  religion?: StringResult
  profession?: StringResult
  maritalStatus?: StringResult
  residentialStatus?: StringResult
  employer?: StringResult
  sex?: StringResult
  sponsor?: StringResult
  bloodType?: StringResult
  dateOfBirth?: DateResult<StringResult>
  dateOfIssue?: DateResult<StringResult>
  dateOfExpiry?: DateResult<StringResult>
  dateOfExpiryPermanent?: boolean
  documentNumber?: StringResult
  personalIdNumber?: StringResult
  documentAdditionalNumber?: StringResult
  documentOptionalAdditionalNumber?: StringResult
  additionalPersonalIdNumber?: StringResult
  issuingAuthority?: StringResult
  visaType?: StringResult
  driverLicenseDetailedInfo?: DriverLicenceDetailedInfo<StringResult>
  documentSubtype?: StringResult
  remarks?: StringResult
  residencePermitType?: StringResult
  manufacturingYear?: StringResult
  vehicleType?: StringResult
  eligibilityCategory?: StringResult
  specificDocumentValidity?: StringResult
  dependentsInfo?: DependentInfo[]
  vehicleOwner?: StringResult
  certificateNumber?: StringResult
  countryCode?: StringResult
  nationalInsuranceNumber?: StringResult
}

export type ScanningMode = "single" | "automatic"
